context:
  version: "2.20.0"

package:
  name: lumen-tui
  version: ${{ version }}

source:
  url: https://github.com/jnsahaj/lumen/archive/refs/tags/v${{ version }}.tar.gz
  sha256: c077740d0f04f6207850f8e3569984e6d6c6decff0272996ba012b52eef9b884

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins -j ${CPU_COUNT} --root ${{ PREFIX }} --path .
        else:
          - cargo auditable install --locked --no-track --bins -j %CPU_COUNT% --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - make
  run:
    - fzf
    - mdcat

tests:
  - script: lumen --help

about:
  homepage: https://github.com/jnsahaj/lumen
  summary: A command-line tool that uses AI to streamline your git workflow - generate commit messages, view diff and explain changes.
  description: |
    Features:
    - Beautiful & Ergonomic Diff Viewer: Review your code with minimal effort
    - Smart Commit Messages: Generate conventional commit messages for your staged changes
    - Git History Insights: Understand what changed in any commit, branch, or your current work
    - Interactive Search: Find and explore commits using fuzzy search
    - Change Analysis: Ask questions about specific changes and their impact
    - Multiple AI Providers: Supports OpenAI, Claude, Groq, Ollama, and more
    - Flexible: Works with any git workflow and supports multiple AI providers
    - Rich Output: Markdown support for readable explanations and diffs (requires: mdcat)
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - claudiushaag
